name: Validate with hassfest

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
#  schedule:
#    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.2"
          
        - name: "Run hassfest validation"
          uses: "home-assistant/actions/hassfest@master"
